name: Trigger Jenkins Pipeline

on:
  pull_request:
    branches:
      - shubhi-test
  workflow_dispatch: 

jobs:
  trigger:
    runs-on: self-hosted

    steps:
    - name: Install jq
      run: |
        sudo yum install jq
          
    - name: Trigger Jenkins Pipeline
      run: |
        
        PR_NUMBER=$(jq -r '.pull_request.number' "$GITHUB_EVENT_PATH")
        PR_TITLE=$(jq -r '.pull_request.title' "$GITHUB_EVENT_PATH")
        SOURCE_BRANCH=$(jq -r '.pull_request.head.ref' "$GITHUB_EVENT_PATH")
        TARGET_BRANCH=$(jq -r '.pull_request.base.ref' "$GITHUB_EVENT_PATH")
        PR_URL=$(jq -r '.pull_request.html_url' "$GITHUB_EVENT_PATH")
        
        payload='{
        "GITHUB_PR_TITLE": "'"${PR_TITLE}"'",
        "GITHUB_PR_NUMBER": "'"${PR_NUMBER}"'",
        "GITHUB_PR_SOURCE_BRANCH": "'"${SOURCE_BRANCH}"'",
        "GITHUB_PR_TARGET_BRANCH": "'"${TARGET_BRANCH}"'",
        "GITHUB_PR_URL": "'"${PR_URL}"'"
        }'
        
        curl --header "Content-Type: application/json" -X POST "https://jenkins.corp.thoughtspot.com/generic-webhook-trigger/invoke?token=shubhi-test" \
          --user shubhi.singh@thoughtspot.com:${{ secrets.JENKINS_TOKEN }} \
          --header "Content-Type: application/json" \
          --data "$payload"
      shell: bash  
    
    - name: Delay for 60 seconds
      run: |
        sleep 60
      shell: bash
        
    - name: Check Jenkins Job Status
      run: |
        PR_NO=$(jq -r '.pull_request.number' "$GITHUB_EVENT_PATH")
        jenkins_job_url="https://jenkins.corp.thoughtspot.com/job/verify-jira-id-shubhi-test/api/json?tree=builds[number,building,result,url]&pretty=true&tree=builds[number,result,url]&xpath=//build[actions/causes/shortDescription[text()=%27PR_NUMBER:%20%24%7BPR_NO%7D%27]][1]"
        echo "$PR_NO"
        echo "$jenkins_job_url"
        jenkins_job_status=$(curl -s "$jenkins_job_url" | jq -r '.builds[0].result')
        # while ["$jenkins_job_status" == "null"]; do
        #   jenkins_job_status=$(curl -s "$jenkins_job_url" | jq -r '.builds[0].result')
        #   if ["$jenkins_job_status" == "null"]; then
        #     echo "Jenkins job is still in progress, waiting..."
        #   fi
        # done

        if [ "$jenkins_job_status" == "FAILURE" ]; then
          echo "Jira ID Validation failed. Please include a Jira ID in your PR"
          exit 1
        elif [ "$jenkins_job_status" == "SUCCESS" ]; then
          echo "Jira ID is present"
        fi

      shell: bash
  
