name: Trigger Jenkins Pipeline

on:
  pull_request:
    branches:
      - shubhi-test
  workflow_dispatch: 

jobs:
  trigger:
    runs-on: self-hosted

    steps:
    - name: Install jq
      run: |
        sudo yum install jq
          
    - name: Trigger Jenkins Pipeline
      run: |
        PR_NUMBER=$(jq -r '.pull_request.number' "$GITHUB_EVENT_PATH")
        PR_TITLE=$(jq -r '.pull_request.title' "$GITHUB_EVENT_PATH")
        SOURCE_BRANCH=$(jq -r '.pull_request.head.ref' "$GITHUB_EVENT_PATH")
        
        curl -vs "https://jenkins.corp.thoughtspot.com/generic-webhook-trigger/invoke?token=shubhi-test&GITHUB_PR_NUMBER=${PR_NUMBER}&GITHUB_PR_TITLE=${PR_TITLE}&GITHUB_PR_SOURCE_BRANCH=${SOURCE_BRANCH}" \
        --user shubhi.singh@thoughtspot.com:${{ secrets.JENKINS_TOKEN }}
      shell: bash  
        
    - name: Check Jenkins Job Status
      run: |
        jenkins_job_url="https://jenkins.corp.thoughtspot.com/job/verify-jira-id-shubhi-test/lastBuild/api/json"
        jenkins_job_status=$(curl -s "$jenkins_job_url" --user "shubhi.singh@thoughtspot.com:${{ secrets.JENKINS_TOKEN }}" | jq -r '.result')
        echo "Result is: $jenkins_job_status"
        if [ "$jenkins_job_status" == "FAILURE" ]; then
          echo "Jenkins job failed"
          exit 1
        elif [ "$jenkins_job_status" == "SUCCESS" ]; then
          echo "Jenkins job succeeded"
        fi
  
