name: Trigger Jenkins Pipeline

on:
  push:
    branches:
      - shubhi-test
  workflow_dispatch: 

jobs:
  trigger:
    runs-on: self-hosted

    steps:
    - name: Trigger Jenkins Pipeline
      run: |
        curl -vs "https://jenkins.corp.thoughtspot.com/generic-webhook-trigger/invoke?token=shubhi-test" \
        --user shubhi.singh@thoughtspot.com:${{ secrets.JENKINS_TOKEN }}
        
    - name: Check Jenkins Job Status
      run: |
        jenkins_job_url="https://jenkins.corp.thoughtspot.com/job/verify-jira-id-shubhi-test/lastBuild/api/json"
        jenkins_job_status=$(curl -s "$jenkins_job_url" | python -c "import sys, json; print(json.load(sys.stdin)['result'])")
        echo "Result is: $jenkins_job_status"
        if [ "$jenkins_job_status" == "FAILURE" ]; then
          echo "Jenkins job failed"
          exit 1
        elif [ "$jenkins_job_status" == "SUCCESS" ]; then
          echo "Jenkins job succeeded"
          break
        fi
  
