name: Trigger Jenkins Pipeline

on:
  push:
    branches:
      - shubhi-test
  workflow_dispatch: 

jobs:
  trigger:
    runs-on: self-hosted

    steps:
    - name: Trigger Jenkins Pipeline
      run: |
        curl -X POST https://jenkins.corp.thoughtspot.com/job/verify-jira-id-shubhi-test/ \
        --user ${{ shubhi.singh@thoughtspot.com }}:${{ secrets.JENKINS_API_TOKEN }}
