name: Trigger Jenkins Pipeline

on:
  pull_request:
    branches:
      - shubhi-test
  workflow_dispatch: 

jobs:
  trigger:
    runs-on: self-hosted

    steps:
    - name: Install jq
      run: |
        sudo yum install jq
          
    - name: Trigger Jenkins Pipeline
      run: |
        PR_NUMBER=$(jq -r '.pull_request.number' "$GITHUB_EVENT_PATH")
        PR_TITLE=$(jq -r '.pull_request.title' "$GITHUB_EVENT_PATH")
        SOURCE_BRANCH=$(jq -r '.pull_request.head.ref' "$GITHUB_EVENT_PATH")
        webhook_payload='{
          "parameter": [
            { "name": "GITHUB_PR_NUMBER", "value": "123" },
            { "name": "GITHUB_PR_TITLE", "value": "Sample PR" },
            { "name": "GITHUB_PR_SOURCE_BRANCH", "value": "feature-branch" }
          ]
        }'
        
        curl -vs "https://jenkins.corp.thoughtspot.com/generic-webhook-trigger/invoke?token=shubhi-test" \
          --user shubhi.singh@thoughtspot.com:${{ secrets.JENKINS_TOKEN }} \
          --header "Content-Type: application/json" \
          --data "$webhook_payload"
      shell: bash  
        
    - name: Check Jenkins Job Status
      run: |
        jenkins_job_url="https://jenkins.corp.thoughtspot.com/job/verify-jira-id-shubhi-test/lastBuild/api/json"
        jenkins_job_status=$(curl -s "$jenkins_job_url" --user "shubhi.singh@thoughtspot.com:${{ secrets.JENKINS_TOKEN }}" | jq -r '.result')
        echo "Result is: $jenkins_job_status"
        if [ "$jenkins_job_status" == "FAILURE" ]; then
          echo "Jenkins job failed"
          exit 1
        elif [ "$jenkins_job_status" == "SUCCESS" ]; then
          echo "Jenkins job succeeded"
        fi
  
