name: Trigger Jenkins Pipeline

on:
  push:
    branches:
      - shubhi-test
  workflow_dispatch: 

jobs:
  trigger:
    runs-on: self-hosted

    steps:
    - name: Trigger Jenkins Pipeline
      run: |
        curl -vs "https://jenkins.corp.thoughtspot.com/generic-webhook-trigger/invoke?token=shubhi-test" \
        --user shubhi.singh@thoughtspot.com:${{ secrets.JENKINS_TOKEN }}
